name: truckle_drivers
description: A new Flutter application.

version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+4
  shared_preferences: ^0.5.3+4
  dio: ^3.0.8
  rxdart: ^0.23.0
  flutter_bloc: ^3.2.0
  equatable: ^0.5.1
  font_awesome_flutter: ^8.2.0
  intl: ^0.16.0
  awesome_dialog: ^1.1.2
  image_cropper: 1.2.1
  flutter_launcher_icons: ^0.7.3
  audioplayers: ^0.13.6
  url_launcher: ^5.1.2
  progress_dialog: ^1.2.0
  connectivity: ^0.4.5+1
  flutter_spinkit: ^3.1.0
  kiwi: ^0.2.0
  shimmer: ^1.0.1
  adhara_socket_io: ^0.3.7
  firebase_messaging: ^6.0.9
  cached_network_image: ^2.0.0
  fancy_bottom_navigation: ^0.3.2
  flutter_image_compress: ^0.6.5+1
  flutter_luban: ^0.1.11
  bubble_bottom_bar: ^1.2.0
  flutter_ringtone_player:
  flutter_app_badger: ^1.1.2
  app_settings: 3.0.1
  flutter_slidable: ^0.5.3
  loader_search_bar: ^1.0.3+3
  geolocator: any
  flutter_rating_bar: ^1.3.0+1
  flutter_local_notifications: ^1.4.4+1
  bubble: ^1.1.9+1
  slide_countdown_clock:
  image_gallery_saver: ^1.2.2
  toast: ^0.1.5
  pin_code_fields:
  country_code_picker: ^1.4.0
  ff_navigation_bar: ^0.1.4
  curved_navigation_bar: ^0.3.2
  carousel_pro:
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.1
  multi_image_picker: ^4.6.1
  esys_flutter_share: ^1.0.2
  provider: ^4.0.2 
  fluttertoast: ^4.0.0









dev_dependencies:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/newLogo.png"
  image_path_ios: "assets/images/newLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/langs/ar.json
    - assets/langs/en.json
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: caira
      fonts:
        - asset: assets/fonts/cairo_regular.ttf
analyzer:
  enable-experiment:
    - spread-collections